/* ============================================================================
 * rivet.data.js — THE SINGLE SOURCE OF INPUT
 * ----------------------------------------------------------------------------
 * Every page, tab, badge, control and value in the Rivet cockpit is rendered
 * from this one object. The real tool injects the same shape:
 *   GET  /api/state   → this object
 *   POST /api/config  → saves RIVET.config.manifest values to .rivet/config.json
 * Open from file:// and it renders read-only from the literal below.
 * ==========================================================================*/
window.RIVET = {
  meta: {
    project: "rivet",
    tagline: "evidence-bound delivery",
    configPath: ".rivet/config.json",
    generatedAt: "2026-06-12T10:00:00Z",
    serverMode: true,          // false => file:// read-only
    refreshSeconds: 15,
    inFlightTasks: ["FEAT-X-01"]
  },

  /* ---- navigation is data too: the shell builds the sidebar from this ---- */
  nav: [
    { group: "Dashboard", mode: "dashboard", items: [
      { id: "overview",     label: "Overview",     icon: "◎" },
      { id: "tasks",        label: "Tasks",        icon: "✅" },
      { id: "requirements", label: "Requirements", icon: "📐" },
      { id: "graph",        label: "Graph",        icon: "🕸️" },
      { id: "activity",     label: "Activity",     icon: "🧾" },
      { id: "files",        label: "Artifacts",    icon: "📁" }
    ]},
    { group: "Config", mode: "config", items: "@sections" }  // expanded from config.sections
  ],

  /* ===================== DASHBOARD DATA ===================== */
  dashboard: {
    completion: { done: 24, total: 27 },
    validates:  { green: 18, red: 1, stale: 4, unproven: 2 },
    drift: 5,
    graphHtml: "graph-placeholder",
    tasks: [
      { id: "DASH-01", title: "evidence dashboard v1", status: "done",
        boundChecks: ["test/dashboard.test.ts"],
        results: { "test/dashboard.test.ts": { passed: true, at: "2026-06-12T09:00:00Z", kind: "unit" } } },
      { id: "GREET-01", title: "personalized greeting endpoint", status: "done",
        boundChecks: ["api/GreetControllerTest#greet"],
        results: { "api/GreetControllerTest#greet": { passed: true, at: "2026-06-12T08:30:00Z", kind: "api" } } },
      { id: "WAVE-02", title: "post-wave worktree cleanup", status: "in_progress",
        boundChecks: ["test/wave-done.test.ts"],
        results: { "test/wave-done.test.ts": { passed: false, at: "2026-06-12T08:50:00Z", kind: "unit",
          tail: "AssertionError: expected worktree branch to be gone\n  at cleanup (wave.ts:88:11)\n  expected: undefined\n  received: 'rivet/wave-02-cleanup'\n\n  1 failing · 14 passing" } } },
      { id: "STEER-01", title: "laws / steering engine", status: "blocked",
        boundChecks: ["test/steering.test.ts"],
        results: { "test/steering.test.ts": { passed: false, at: "2026-06-12T07:40:00Z", kind: "unit",
          tail: "Error: laws.md not found — run `rivet init` first\n  blocked on: STEER-00" } } },
      { id: "FEAT-X-01", title: "intake adapters (github + jira)", status: "in_progress",
        boundChecks: ["test/intake.test.ts", "test/jira-map.test.ts"],
        results: {
          "test/intake.test.ts": { passed: true, at: "2026-06-12T09:20:00Z", kind: "unit" },
          "test/jira-map.test.ts": { passed: false, at: "2026-06-12T09:22:00Z", kind: "unit",
            tail: "TypeError: cannot read epic.children of undefined\n  at mapEpic (jira.ts:42:18)" } } },
      { id: "GRAPH-03", title: "stale-proof drift detector", status: "pending",
        boundChecks: ["test/drift.test.ts"], results: {} }
    ],
    requirements: [
      { id: "REQUIREMENT_GREET_01", title: "personalized greeting", proven: true,
        criteria: [{ id: "AC1", proof: "green" }, { id: "AC2", proof: "green" }] },
      { id: "REQUIREMENT_GREET_02", title: "missing-name default path", proven: false,
        criteria: [{ id: "AC1", proof: "stale" }, { id: "AC2", proof: "unproven" }] },
      { id: "NFR_LATENCY_01", title: "greeting p95 < 80ms", proven: false,
        criteria: [{ id: "AC1", proof: "red" }] },
      { id: "REQUIREMENT_INTAKE_01", title: "github issue → task mirror", proven: false,
        criteria: [{ id: "AC1", proof: "green" }, { id: "AC2", proof: "stale" }] },
      { id: "ADR_GRAPH_01", title: "revitify is the default graph provider", proven: true,
        criteria: [{ id: "AC1", proof: "green" }] }
    ],
    approvals: [
      { at: "2026-06-11T21:00:00Z", approver: "Pratiyush", taskIds: ["GREET-01", "REQUIREMENT_GREET_01"], commit: "9d9cc2d5" }
    ],
    governance: [
      { at: "2026-06-12T07:10:00Z", kind: "unlock", detail: ".rivet/config.json for 30m", who: "Pratiyush" },
      { at: "2026-06-11T18:02:00Z", kind: "lock",   detail: ".rivet/config.json (GATE-PROTECT)", who: "engine" }
    ],
    activity: [
      { at: "2026-06-12T09:22:00Z", icon: "❌", text: "check test/jira-map.test.ts → FEAT-X-01", meta: "claude" },
      { at: "2026-06-12T09:20:05Z", icon: "✅", text: "check test/intake.test.ts → FEAT-X-01", meta: "claude" },
      { at: "2026-06-12T09:00:30Z", icon: "🏁", text: "task DASH-01 → done", meta: "engine" },
      { at: "2026-06-12T09:00:12Z", icon: "✅", text: "check test/dashboard.test.ts → DASH-01", meta: "Pratiyush · claude" },
      { at: "2026-06-12T08:50:02Z", icon: "❌", text: "check test/wave-done.test.ts → WAVE-02", meta: "claude" },
      { at: "2026-06-12T08:30:00Z", icon: "✅", text: "check api/GreetControllerTest#greet → GREET-01", meta: "claude" },
      { at: "2026-06-11T21:00:00Z", icon: "🔏", text: "approve GREET-01 · REQUIREMENT_GREET_01", meta: "Pratiyush" }
    ],
    files: [
      { name: "laws.md", content: "# Project Laws\n\n## Hard rules\n- A task is **not done** until its bound checks pass — *and* the proof is fresh (not stale).\n- Commits are authored by the human; the agent may only co-author.\n- Every fixed bug leaves behind a regression check.\n\n## Severity\n| Rule | On break |\n|---|---|\n| done-on-fail | `error` |\n| qualified-ids | `warn` |\n" },
      { name: "learnings.md", content: "# Learnings\n\n## 2026-06-12 — Fixtures must pin git config\n- **Trigger:** host `init.defaultBranch` leaked into fixtures and broke `wave-done`.\n- **Lesson:** pin `git init -b main` and push `HEAD:main`.\n- **Promoted to:** `check:test/wave.test.ts`\n\n> Repeated twice before promotion. `learning.warnOnRepeat` would have caught it.\n" },
      { name: "specs/greeting.md", content: "# Feature: Greeting API\n\n## REQUIREMENT_GREET_01 — personalized greeting\nWHEN a `GET /greet?name=Ada` request arrives\nTHEN the system SHALL respond `200` with `\"Hello, Ada\"`.\n\n@check kind=api ref=GreetControllerTest#greet\n\n## REQUIREMENT_GREET_02 — missing-name default\nWHEN `name` is absent THEN the system SHALL respond `\"Hello, there\"`.\n\n@check kind=api ref=GreetControllerTest#greetDefault\n" },
      { name: "RESUME.md", content: "# RESUME\n\n## THE ONE OPEN ACTION\n→ **WAVE-02** — post-wave worktree cleanup *(check failing)*\n\n## Then\n1. FEAT-X-01 — fix `jira-map` epic mapping\n2. unblock STEER-01 (needs `laws.md`)\n" },
      { name: "TRACKING.md", content: "# TRACKING\n\n| Requirement | Proof | Approved |\n|---|---|---|\n| REQUIREMENT_GREET_01 | 🟢 | ✅ |\n| REQUIREMENT_GREET_02 | 🟣 | — |\n| NFR_LATENCY_01 | 🔴 | — |\n" },
      { name: "approvals/2026-06-11-GREET-01.md", content: "# Approval — GREET-01\n- **Approved by:** Pratiyush\n- **Commit:** `9d9cc2d5`\n- **Proof:** api/GreetControllerTest#greet 🟢\n" }
    ]
  },

  /* ===================== CONFIG DATA ===================== */
  config: {
    sections: [
      { id: "project",  icon: "📦", blurb: "Identity the boards and journal read from." },
      { id: "mode",     icon: "🧭", blurb: "How work gets routed to agents." },
      { id: "intake",   icon: "📥", blurb: "Where new work is ingested from." },
      { id: "spec",     icon: "📐", blurb: "How plans and acceptance criteria are shaped." },
      { id: "build",    icon: "🔨", blurb: "Coding discipline: tests, fences, retries, deps." },
      { id: "verify",   icon: "✅", blurb: "The proof engine — checks, stacks, runners." },
      { id: "review",   icon: "🔎", blurb: "Second-pass review before merge." },
      { id: "pr",       icon: "🔀", blurb: "Branching, CI and merge policy." },
      { id: "memory",   icon: "🧠", blurb: "Resume, journaling and drift detection." },
      { id: "parallel", icon: "⚡", blurb: "Concurrent worktree execution." },
      { id: "dashboard",icon: "📊", blurb: "The evidence dashboard + notifications." },
      { id: "rules",    icon: "⚖️", blurb: "Laws, conflicts and id hygiene." },
      { id: "learning", icon: "🌱", blurb: "Capturing and promoting learnings." },
      { id: "gates",    icon: "🛡️", blurb: "The moat: what must hold before done." },
      { id: "graphify", icon: "🕸️", blurb: "The code-graph provider." }
    ],
    manifest: [
      { section:"project", key:"name", path:"project.name", type:"string",
        value:"rivet", default:"untitled", changed:true,
        description:"Human-readable project name used in board headers and journal metadata." },
      { section:"project", key:"platforms", path:"project.platforms", type:"enum[]",
        allowed:["java-maven","java-gradle","spring","quarkus","node","typescript","electron","react","next","angular","python"],
        value:["typescript","node"], default:[], changed:true,
        description:"Codebase platforms (an ARRAY — polyglot is normal). Drives stack inference and init best-practice packs. NOT runner ids." },
      { section:"mode", key:"routing", path:"mode.routing", type:"enum",
        allowed:["auto","pick","auto-override"], value:"auto", default:"auto", changed:false,
        description:"How work is routed to agents. auto picks the lane; pick always asks you; auto-override runs auto but lets you veto." },
      { section:"mode", key:"confirmFirst", path:"mode.confirmFirst", type:"boolean",
        value:true, default:true, changed:false,
        description:"Pause for confirmation before the first task of a run kicks off." },
      { section:"mode", key:"researchMode", path:"mode.researchMode", type:"boolean",
        value:false, default:false, changed:false,
        description:"Bias agents toward exploration + write-ups over shipping code. Useful for spikes." },
      { section:"intake", key:"sources", path:"intake.sources", type:"enum[]",
        allowed:["raw","github","gitlab","jira"], value:["raw"], default:["raw"], changed:false,
        description:"Where new work is ingested from. raw = freeform prompts; the rest mirror external trackers." },
      { section:"intake", key:"jiraEpic", path:"intake.jiraEpic", type:"enum",
        allowed:["mirror","replan","ask"], value:"ask", default:"ask", changed:false,
        description:"When a Jira epic lands: mirror it 1:1, replan into Rivet's own breakdown, or ask each time." },
      { section:"intake", key:"writeBack", path:"intake.writeBack", type:"boolean",
        value:false, default:false, changed:false,
        description:"Push status + links back to the originating tracker as tasks complete." },
      { section:"spec", key:"style", path:"spec.style", type:"enum",
        allowed:["checklist","stories","both"], value:"both", default:"checklist", changed:true,
        description:"Shape of the generated plan: terse checklists, user stories, or both side by side." },
      { section:"spec", key:"acceptanceCriteria", path:"spec.acceptanceCriteria", type:"enum",
        allowed:["tool-drafts","user-writes"], value:"tool-drafts", default:"tool-drafts", changed:false,
        description:"Who authors acceptance criteria — the tool drafts then you edit, or you write from scratch." },
      { section:"spec", key:"criteriaFormat", path:"spec.criteriaFormat", type:"enum",
        allowed:["gherkin","ears","plain","mixed"], value:"mixed", default:"gherkin", changed:true,
        description:"Criteria syntax. Gherkin (default): Scenario / Scenario Outline + Examples. Both grammars always parse; off-format criteria lint (warn-only)." },
      { section:"spec", key:"breakdownDepth", path:"spec.breakdownDepth", type:"number",
        value:3, default:3, changed:false, min:1, max:6,
        description:"How many levels deep the planner decomposes an epic before stopping." },
      { section:"spec", key:"gapHunting", path:"spec.gapHunting", type:"enum",
        allowed:["off","propose","auto"], value:"propose", default:"propose", changed:false,
        description:"Actively look for missing requirements. propose surfaces gaps for review; auto files them." },
      { section:"spec", key:"livingPlan", path:"spec.livingPlan", type:"enum",
        allowed:["frozen","update-ask","update-auto"], value:"update-ask", default:"update-ask", changed:false,
        description:"Whether the plan can evolve mid-run as you learn. frozen locks scope after kickoff." },
      { section:"build", key:"tests", path:"build.tests", type:"enum",
        allowed:["tdd","code-first","either"], value:"tdd", default:"either", changed:true,
        description:"Test discipline. tdd writes the failing check first; code-first tests after; either lets the agent choose." },
      { section:"build", key:"fileFence", path:"build.fileFence", type:"boolean",
        value:true, default:true, changed:false,
        description:"Confine each task's writes to a declared set of files; out-of-fence edits are blocked." },
      { section:"build", key:"retryLimit", path:"build.retryLimit", type:"number",
        value:3, default:3, changed:false, min:0, max:10,
        description:"How many times an agent may retry a failing check before escalating to you." },
      { section:"build", key:"newDeps", path:"build.newDeps", type:"enum",
        allowed:["ask","auto","ask-big"], value:"ask-big", default:"ask", changed:true,
        description:"Adding a dependency: always ask, auto-approve, or only ask for heavy/transitive-heavy ones." },
      { section:"verify", key:"blockDoneOnFail", path:"verify.blockDoneOnFail", type:"boolean",
        value:true, default:true, changed:false,
        description:"A task cannot be marked done while bound checks fail — or while a passing proof is STALE (recorded on an older code tree)." },
      { section:"verify", key:"defaultStack", path:"verify.defaultStack", type:"string",
        value:null, default:null, changed:false, placeholder:"node-vitest",
        description:"Stack used when --stack is omitted. Resolution: flag → this → inferred from platforms → error." },
      { section:"verify", key:"coverage", path:"verify.coverage", type:"number",
        value:null, default:null, changed:false, min:0, max:100, unit:"%", nullable:true,
        description:"Minimum line coverage to allow done. null = don't gate on coverage." },
      { section:"verify", key:"everyCriterionNeedsCheck", path:"verify.everyCriterionNeedsCheck", type:"boolean",
        value:false, default:false, changed:false,
        description:"Refuse to mark a requirement proven unless every acceptance criterion has a bound check." },
      { section:"verify", key:"kindRunners", path:"verify.kindRunners", type:"record",
        value:{ lint:{ cmd:"npx", args:["eslint","."] } }, default:{}, changed:true,
        recordShape:{ cmd:"string", args:"string[]" },
        description:"Kind-level runner templates (lint, audit, visual…). {ref}/{file}/{name} placeholders. Precedence: kindRunners > runners > builtin." },
      { section:"verify", key:"app", path:"verify.app", type:"object",
        fields:[ {key:"start", type:"string[]"}, {key:"readyUrl", type:"string", placeholder:"http://localhost:3000/health"}, {key:"readyTimeoutMs", type:"number", min:0, max:120000, unit:"ms"} ],
        value:{ start:["npm","run","dev"], readyUrl:"http://localhost:3000", readyTimeoutMs:30000 },
        default:{ start:[], readyUrl:null, readyTimeoutMs:30000 }, changed:true,
        description:"How to boot the app for runApp / UI checks: start command, readiness URL, and how long to wait." },
      { section:"review", key:"separateReviewer", path:"review.separateReviewer", type:"boolean",
        value:true, default:true, changed:false,
        description:"Run review with a fresh agent that didn't write the code, to avoid author bias." },
      { section:"review", key:"passes", path:"review.passes", type:"number",
        value:1, default:1, changed:false, min:0, max:4,
        description:"Number of review passes before a change is eligible to merge." },
      { section:"review", key:"fixFindings", path:"review.fixFindings", type:"enum",
        allowed:["auto","ask","report"], value:"ask", default:"ask", changed:false,
        description:"What to do with review findings: auto-fix, ask first, or just report them." },
      { section:"pr", key:"merge", path:"pr.merge", type:"enum",
        allowed:["auto-on-green","manual"], value:"manual", default:"manual", changed:false,
        description:"Merge policy. auto-on-green merges once all checks pass and review clears; manual waits for you." },
      { section:"pr", key:"waitForCI", path:"pr.waitForCI", type:"boolean",
        value:true, default:true, changed:false,
        description:"Block merge until remote CI is green, not just local checks." },
      { section:"pr", key:"commitAuthor", path:"pr.commitAuthor", type:"enum",
        allowed:["user","co-author"], value:"user", default:"user", changed:false,
        description:"Commits are authored by the human; co-author adds the agent as Co-authored-by trailer." },
      { section:"pr", key:"branchPattern", path:"pr.branchPattern", type:"string",
        value:"rivet/{taskId}-{slug}", default:"rivet/{taskId}-{slug}", changed:false,
        description:"Branch name template. {taskId} and {slug} are interpolated per task." },
      { section:"memory", key:"crashResume", path:"memory.crashResume", type:"boolean",
        value:true, default:true, changed:false,
        description:"Persist enough state to resume a run cleanly after a crash or restart." },
      { section:"memory", key:"journal", path:"memory.journal", type:"enum",
        allowed:["full","milestones"], value:"full", default:"milestones", changed:true,
        description:"Journal verbosity. full logs every check + decision; milestones logs only task transitions." },
      { section:"memory", key:"driftDetection", path:"memory.driftDetection", type:"boolean",
        value:true, default:true, changed:false,
        description:"Mark passing proofs STALE when the code they ran against has since changed." },
      { section:"parallel", key:"enabled", path:"parallel.enabled", type:"boolean",
        value:true, default:false, changed:true,
        description:"Run independent tasks concurrently in isolated worktrees." },
      { section:"parallel", key:"waveSize", path:"parallel.waveSize", type:"number",
        value:6, default:6, changed:false, min:1, max:24,
        description:"Max concurrent worktree tasks (~6 avoids rate-limit wipeouts)." },
      { section:"parallel", key:"onFileClash", path:"parallel.onFileClash", type:"enum",
        allowed:["serialize","ask","fail"], value:"serialize", default:"serialize", changed:false,
        description:"When two in-flight tasks want the same file: serialize them, ask, or fail the later one." },
      { section:"dashboard", key:"enabled", path:"dashboard.enabled", type:"boolean",
        value:true, default:true, changed:false,
        description:"Generate the evidence dashboard (the Dashboard views)." },
      { section:"dashboard", key:"updates", path:"dashboard.updates", type:"enum",
        allowed:["live","on-demand"], value:"live", default:"on-demand", changed:true,
        description:"live: boards + dashboard regenerate automatically after every task done / check run." },
      { section:"dashboard", key:"refreshSeconds", path:"dashboard.refreshSeconds", type:"number",
        value:15, default:15, changed:false, min:5, max:120, unit:"s",
        description:"How often the dashboard + config studio poll for changes on disk." },
      { section:"dashboard", key:"notify", path:"dashboard.notify", type:"object",
        fields:[ {key:"channels", type:"enum[]", allowed:["slack","email","webhook","desktop"]}, {key:"on", type:"enum[]", allowed:["done","fail","approval","drift"]} ],
        value:{ channels:["slack"], on:["fail","approval"] },
        default:{ channels:[], on:[] }, changed:true,
        description:"Where and when to send notifications about run events." },
      { section:"rules", key:"onConflict", path:"rules.onConflict", type:"enum",
        allowed:["stop","warn","prefer-project"], value:"warn", default:"warn", changed:false,
        description:"When two laws conflict: stop the run, warn and continue, or prefer the project-level law." },
      { section:"rules", key:"inheritPersonal", path:"rules.inheritPersonal", type:"boolean",
        value:false, default:false, changed:false,
        description:"Layer your personal ~/.rivet laws on top of the project's. Off keeps runs reproducible across machines." },
      { section:"rules", key:"requireQualifiedIds", path:"rules.requireQualifiedIds", type:"enum",
        allowed:["warn","error","off"], value:"warn", default:"warn", changed:false,
        description:"Requirement ids must self-describe: REQUIREMENT_/NFR_/ADR_. Legacy R- ids parse but lint at this severity." },
      { section:"learning", key:"capture", path:"learning.capture", type:"boolean",
        value:true, default:true, changed:false,
        description:"Record learnings (root causes, fixes, gotchas) into learnings.md as runs proceed." },
      { section:"learning", key:"promoteToRules", path:"learning.promoteToRules", type:"enum",
        allowed:["off","propose","auto"], value:"propose", default:"propose", changed:false,
        description:"Turn repeated learnings into enforced laws. propose drafts; auto promotes silently." },
      { section:"learning", key:"bugToTest", path:"learning.bugToTest", type:"boolean",
        value:true, default:true, changed:false,
        description:"Every fixed bug must leave behind a regression check that would have caught it." },
      { section:"learning", key:"warnOnRepeat", path:"learning.warnOnRepeat", type:"boolean",
        value:true, default:true, changed:false,
        description:"Warn when the agent is about to repeat a mistake already recorded in learnings." },
      { section:"gates", key:"facts", path:"gates.facts", type:"enum",
        allowed:["on","off"], value:"on", default:"on", changed:false,
        description:"Require machine-checkable facts (not prose) behind every gate decision." },
      { section:"gates", key:"negativeFloor", path:"gates.negativeFloor", type:"enum",
        allowed:["on","off"], value:"on", default:"on", changed:false,
        description:"Every requirement needs ≥1 negative/failure criterion or graph build flags it. Prose mandates are ignorable; floors aren't." },
      { section:"gates", key:"require", path:"gates.require", type:"enum[]",
        allowed:["tests","review","security","coverage","negative-floor"], value:["tests","review"], default:["tests"], changed:true,
        description:"Gates that must pass before any task is eligible for done." },
      { section:"gates", key:"packs", path:"gates.packs", type:"record",
        value:{ "api-baseline":{ sections:["verify"], kinds:["api"], triggers:["platforms:node"] } }, default:{}, changed:true,
        recordShape:{ generic:true },
        description:"Named gate packs: bundles of sections/kinds/triggers applied together. Edited as JSON per entry." },
      { section:"graphify", key:"provider", path:"graphify.provider", type:"enum",
        allowed:["revitify","graphify"], value:"revitify", default:"revitify", changed:false,
        description:"Who builds the code graph. revitify (bundled TS, zero installs) or the external Python graphify (multi-modal, opt-in)." },
      { section:"graphify", key:"outDir", path:"graphify.outDir", type:"string",
        value:".rivet/graph", default:".rivet/graph", changed:false,
        description:"Directory the built graph artifacts are written to." },
      { section:"graphify", key:"freshness", path:"graphify.freshness", type:"enum",
        allowed:["per-run","daily","manual"], value:"per-run", default:"per-run", changed:false,
        description:"How often the code graph is rebuilt. per-run rebuilds before each verify wave." }
    ]
  }
};
