import type { VerifiedTraceabilityGraph, GraphEdge, ProofState } from "../graph/types.js";
import type { Requirement } from "../spec/ears.js";
import type { Task } from "../state/tasks.js";

/**
 * Graph-derived PR body — the traceability report no incumbent tool can produce, because none of
 * them have proven edges. Everything here is read from the VTG + journal; nothing is claimed.
 */

export interface PrBodyInput {
  title: string;
  requirements: Requirement[];
  graph: VerifiedTraceabilityGraph;
  tasks: Task[];
  approvals: string[];
  headSha?: string;
}

const LIGHT: Record<ProofState, string> = {
  green: "🟢 green",
  red: "🔴 red",
  stale: "🟣 stale",
  unproven: "⚪ unproven",
};

export function buildPrBody(input: PrBodyInput): string {
  const validatesByCriterion = new Map<string, GraphEdge[]>();
  for (const e of input.graph.edges) {
    if (e.kind !== "validates") continue;
    const list = validatesByCriterion.get(e.to) ?? [];
    list.push(e);
    validatesByCriterion.set(e.to, list);
  }

  let totalCriteria = 0;
  let provenCriteria = 0;
  const rows: string[] = [];
  for (const req of input.requirements) {
    for (const c of req.criteria) {
      totalCriteria++;
      // Worst-of obligation semantics (FIX-PRMATH-01): EVERY binding must be green — the headline
      // number must be the strictest one, matching rollupRequirements.
      const edges = validatesByCriterion.get(c.id) ?? [];
      const green = edges.length > 0 && edges.every((e) => e.proof === "green");
      if (green) provenCriteria++;
      const proofs =
        edges.length === 0
          ? "⚪ no check bound"
          : edges
              .map((e) => `${LIGHT[e.proof]} \`${e.lastCheck?.ref ?? e.from.replace(/^test:/, "")}\``)
              .join("<br>");
      rows.push(`| ${req.id} | ${c.id} | ${proofs} |`);
    }
  }

  const coverage = totalCriteria === 0 ? 0 : Math.round((provenCriteria / totalCriteria) * 100);
  const drifted = input.graph.edges.filter(
    (e) => e.kind === "validates" && (e.proof === "red" || e.proof === "stale"),
  ).length;
  const doneTasks = input.tasks.filter((t) => t.status === "done");

  return [
    `## ${input.title}`,
    "",
    `**Binding coverage:** ${provenCriteria}/${totalCriteria} acceptance criteria proven green (${coverage}%)` +
      (input.headSha ? ` at \`${input.headSha.slice(0, 8)}\`` : ""),
    drifted > 0 ? `\n> ⚠️ **${drifted} proof(s) red/stale** — this PR should not merge until re-verified.` : "",
    "",
    "### Traceability (generated from the Verified Traceability Graph)",
    "",
    "| Requirement | Criterion | Proof |",
    "|---|---|---|",
    ...rows,
    "",
    "### Tasks",
    "",
    ...input.tasks.map(
      (t) => `- ${t.status === "done" ? "✅" : "⬜"} **${t.id}** ${t.title} (${t.status})`,
    ),
    "",
    input.approvals.length > 0
      ? `### Recorded approvals\n\n${input.approvals.map((a) => `- \`${a}\``).join("\n")}`
      : "### Recorded approvals\n\n- _none yet_",
    "",
    `---`,
    `_${doneTasks.length}/${input.tasks.length} task(s) done · generated by Rivet — every requirement riveted to a passing check._`,
  ]
    .filter((l) => l !== "")
    .join("\n");
}
